<a href="https://colab.research.google.com/github/dnhirapara/049_DarshikHirapara/blob/main/Lab_01_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# two matrices
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[2, 3], [5, 7], [11, 13]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  3]
 [ 5  7]
 [11 13]]


In [ ]:
# Randomly Initalize that array
arr3 = np.random.rand(3, 4)
print(arr3)

[[0.67732752 0.89444855 0.75374491 0.15666318]
 [0.18257976 0.74837981 0.90157672 0.29441459]
 [0.68302808 0.81336901 0.96874464 0.13336037]]


In [ ]:
# Perform matrix multiplication
res = np.dot(arr1, arr2)
print(res)

[[ 45  56]
 [ 99 125]]


In [ ]:
# Perform elementwise matrix multiplication
res = np.zeros((len(arr1), len(arr2[0])))
for i in range(len(arr1)):
    for j in range(len(arr2[0])):
        for k in range(len(arr2)):
            res[i][j] += arr1[i][k] * arr2[k][j]
print(res)

[[ 45.  56.]
 [ 99. 125.]]


In [ ]:
# Find mean of first matrix
res = np.mean(arr1)
print(res)

3.5


In [ ]:
# Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

data = pd.read_csv("/content/drive/MyDrive/ML_Labs/lab1/mtcars.csv")
del data['model']
mean_center = data.apply(lambda ele: ele - ele.mean())
print(mean_center.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
